services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_DBNAME: user
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: urlshortener_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
