# Указываем базовый образ с Go 1.24
FROM golang:1.24-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./

# Скачиваем зависимости
RUN go mod download

# Копируем остальные файлы
COPY . .

# Собираем бинарник
RUN go build -o url-shortener ./cmd

# Указываем порт и команду запуска
EXPOSE 8080

CMD ["./url-shortener"]
